eureka:
  client:
    serviceUrl:
      defaultZone: http://sysadmin:Tj20jq7T@192.168.1.34:8503/eureka/
  #    http://sysadmin:Tj20jq7T@192.168.1.35:8500/eureka/
  #    ,
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
#  prefer-ip-address: true
server:
  port: 8002

spring:
  application:
    name: sso-client
  datasource:
    url: jdbc:mysql://192.168.1.5:3306/sso?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: TjTaA124#
    driver-class-name: com.mysql.jdbc.Driver
#    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
    tomcat:
      max-active: 20
  # thymeleaf:
  #   mode: HTML5
  #   #编码 可不用配置
  #   encoding: UTF-8
  #   #内容类别,可不用配置
  #   cache: false
  #   #配置模板路径，默认是templates，可以不用配置
  #   servlet:
  #     content-type: text/html
  # mvc:
  #   static-path-pattern: /static/**
  main:
    allow-bean-definition-overriding: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
logging:
  level:
    root: DEBUG
jwt:
  moduleName: SSO.CLIENT