server:
  port: 7077

spring:
  thymeleaf:
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    servlet:
      content-type: text/html
  application:
    name: sso-server-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://sysadmin:Tj20jq7T@192.168.1.35:8502/eureka/,http://sysadmin:Tj20jq7T@192.168.1.34:8503/eureka/
  instance:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

zuul:
  sensitive-headers: Authorization
  add-proxy-headers: true
  routes:
    sso-server:
     path: /api/**
     serviceId: sso-server








